### ISSUE TITLE
Remove prints and pointless comments from __init__

### ISSUE THREAD

**Issue by kieran-lemayai** [lemay-ai/smallCompanyType2.0#2]
```
    def __init__(self):
        models_dir = path.join(path.dirname(__file__), 'models')
        #self.dnn_model = load_model(models_dir+'/0_1024_companySector_model.h5')
        #print(models_dir)
        print(__file__)
        print(path.dirname(__file__))
        print(models_dir)
        self.dnn_model = load_model(models_dir+'/company_classifier.h5')
        infile = open(models_dir+ '/encode.pkl','rb')
        #infile = open(models_dir + '/encode.pkl','rb')
        self.enc = pickle.load(infile)
        infile.close()
```

- Prints that are clearly there just for debugging shouldn't be in mainline code
- Useless comment of identical line
- In general, don't leave commented-out lines. Comments should be used for...commenting your code, not paranoiacally preserving old code you're afraid to lose.
- Replace `infile = open` with a context enclosure, i.e. `with open(fpath) as infile:`

**Comment by HershelCK** [comment]
All issues mentioned were addressed. Changes were committed to code.
