### ISSUE TITLE
Clean up `getCompanyEncoding`

### ISSUE THREAD

**Issue by kieran-lemayai** [lemay-ai/smallCompanyType2.0#3]
```
    #Get a one-hot encoding for a company name string
    def getCompanyEncoding(self, name):
        row = np.zeros(300)
        for i in range(len(name)):
            row[i]=ord(name[i])
        #clip if too long
        row = row[:30]
        #extend if too short
        nrow = np.zeros(30)
        for i in range(30):
            nrow[i]=row[i]
        #add a dimension
        nrow=nrow[np.newaxis,:]
        test_tensor = self.enc.transform(nrow)
        return test_tensor
```

- Although it's "clip if too long" there's no clip statement
- There's also no point in allocating a length-300 vector if you're just going to use the top 30 elements, you're just wasting the user's memory
- If you need a copy of a vector (nrow), use `np.copy`
- You also clearly don't need a copy
- In general I'm not clear on what this code is supposed to *do* and I feel like it can be even further simplified.

**Comment by HershelCK** [comment]
You are generally correct that this code can be written more efficiently.  The reason why we initialized a vector row of 300 is to handle large text strings of business names. The memory usage aspect is trivial and I didn't want to run into any index out of range errors. The code can be optimized further but for now the code is functional as is.
