### ISSUE TITLE
install dependencies typo?

### ISSUE THREAD

**Issue by dcshapiro** [lemay-ai/smallCompanyType2.0#7]
In https://github.com/lemay-ai/smallCompanyType2.0/blob/master/setup.py
Line 9:
numpy>==1.13.3
should this be numpy>=1.13.3 ?

I think *>==* is a typo, right? 

https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by HershelCK** [comment]
Looks like a typo - I fixed it.
